name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: chawyehsu/setup-moonup@8b0340aa45016c02c776cbe42a7856b371e610bf # v1.0.0
      - run: moon version --all
      - run: cd moonbit && moon update && moon install
      - run: make build
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: crystal.wasm
          path: crystal.wasm
          overwrite: true
          retention-days: 1
  e2e:
    name: crystal on ${{ matrix.os }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: moonrepo/setup-toolchain@3927d571963592235146e8e0b5261206954796a2 # v0.6.0
        with:
          cache: false
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: crystal.wasm
      - run: uname -a
      - run: proto plugin add crystal "file://$GITHUB_WORKSPACE/crystal.wasm"
        env:
          PROTO_CONFIG_MODE: global
      - run: proto plugin info crystal
      - run: proto versions crystal
      - run: proto install crystal 1.17.1
      - run: proto run crystal -- --version
      - run: crystal --version
      - run: shards --version
      - run: shards install && crystal run main.cr
        working-directory: test
      - run: proto install crystal latest
      - run: echo "1.17.0" > .crystal-version
      - run: proto install crystal
      - run: crystal --version | grep "1.17.0"
  release:
    if: github.ref_type == 'tag'
    needs:
      - e2e
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: crystal.wasm
      - run: gh release create ${{ github.ref_name }} crystal.wasm --title ${{ github.ref_name }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ github.token }}
